services:
  clicks:
    image: clickhouse/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    ulimits:
      nofile: 262144
    environment:
      CLICKHOUSE_USER: "userTest"
      CLICKHOUSE_PASSWORD: "passwordTest"
  app:
    build: .
    ports:
      - "3101:3101"
      - "3102:3102"
    depends_on:
      - clicks
    environment:
      CLICKHOUSE_DSN: "tcp://clicks:9000?username=userTest&password=passwordTest"

